[tool.black]
line-length = 100
target-version = ["py312"]
include = "\\.py$"

[tool.ruff]
line-length = 100
target-version = "py312"
exclude = ["migrations"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "Q", "UP"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.12"
plugins = []
ignore_missing_imports = true
pretty = true
strict_optional = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_return_any = true
